from random import randint

TEXT = {
    'intro_p1' : 
        ['salam\n', 
        'dorood\n',
        'chetori to\n',
        'salam vahshi\n',
        'salam mehrabon\n',
        'dorod to rohet\n',
        'dorod to rot\n',
        'dorod be sharafet\n'],
    'intro_p1.5' :
        ['khob bezar bazi ro begam: \n',
         'darmorede bazi: \n',
         'in bazi intorie ke: \n',
         'tozihate bazi: \n',
         'midonam balad nisti bezar tozih bazi ro begam: \n',
         'khob bebin bazi intorie ke: \n',
         'enghadr ke noobee bezar aval bazi ro begam: \n',
         'khob ghashangam bezar bazi ro behet begam: \n',
         'bebin daaa bazi intorie ke: \n'],
    'intro_p2' :
        ['vaghei ia keik -_- ',
         'asli ia mashghi '],
    'intro_p3' :
        ['az ass avordi ',
         'shans avordi ',
         'az ie jaee avordi ',
         'khosh shans bodi '],
    'continue' :
        ['khob baraie edame ie dokeme bezan.\n',
         'baraie edame ie dokeme bezan amo bebine.\n',
         'baraie edame kalat ro bekob ro kibord -_-\n',
         'ie dokme bezan berim baraie edame :)\n'],
    'get_value_p1' : 
        ['khob bia esmet ro be amo bego: ',
         'esm: ',
         'esmet chie bache khoshgel: ',
         'Enter your name (masalan man ie barname kharejiam): ',
         'jana bia va namat ro be ma bego (khodam az neveshtan in halam bad shod): ',
         'aval esmet ro begooooo: ',
         'asl bede, nachie manzoram esmete: '],
    'get_value_p2' :
        ['esme ghashangi dari :).\n',
         'emmmm khob bashe belakhare in ham esme dige. -_-\n',
         'ba in ke ziad baram mohem nist vali khob.\n',
         'man farz mikonam ke esmet ro dorost gofti.\n',
         'esmet vaghean ine. baaaashe\n',
         'khob hala shomaratam bede :). inja na to telgeram ;).\n',
         'emmmm hichi. nemikham az esmet irad begiram.\n'],
    'player_gun_p1' :
        ['khob aslahe be daste to.\n',
         'bia to bezan.\n',
         'bia in gun baraie to baladi estefade koni dige!!!.\n',
         'in ro begir dasted. chizi nist selahe.\n',
         'in selah ro begir.\n'],
    'true_value_p1' : 
        ['khobe goftam behet -_-.\n',
         'iani harfe man barat vazeh nabod!!!.\n',
         'gagooli ia khodet ro zadi be gagooli?\n',
         'nemifahmi ia khodet ro zadi be nafahmi?\n',
         'alan dost daram bebinam toie maghzet che khabare?\n',
         'alan masalan omadi moch begiri -_-.\n',
         'gov -_-.\n'],
    'print_shots_p1' : 
        ['chesmet ro tiz kon ke hamin ie bar neshon midam.\n',
         'faghat talash kon bebini chand ta aslie, chand ta mashghi.\n',
         'cheshmat ro baz kon va bebin chandtash mashgi.\n',
         'cheshmat ro baz kon va bebin chandtash vaghei.\n',
         'deghat kon chon hamin ie bar neshon midam\n'],
    'before_pTOe' :
        ['khob dari kar manteghi mikoni -_-.\n',
         'hoe hoe on aslahe ro movazeb bash.\n',
         'bebin manam nobatam mishe dige.\n',
         'male in harfa nisti.\n',
         'khosgel mishi gun dasted migiri :).\n',
         'emmmm komak nemikhai?\n',
         'baladi ba on gun kar koni?\n'],
    'before_pTOp' :
        ['oskol khodet ro mikhai bezani???\n',
         'entekhab khobi kardi -_-.\n',
         'aha hamon khodet ro bezan khobe.\n',
         'mikhai mashe ro khodam bekesham???\n',
         'khod zani mikoni??? khobe.\n',
         'oskoli dige. bezan be khodet.\n',
         'khod koshi dost dari ha???\n'],
    'after_pTOe_T' :
        ['kheir nabini dard dasht.\n',
         'aeeee dard dasht. \n',
         'aeeee khord. cheatery mage???\n',
         'kheir nabini az koja midonesti pore???\n',
         'bisha#%$@ chera mizani\n',
         'arom vahshi tiret khord behem.\n'],
    'after_pTOp_T' :
        ['khod zani kardi ke.\n',
         'cheghadr nooby khodet ro zadi.\n',
         'baba chera khod zani mikoni.\n',
         'nooby dige.\n',
         'bebinam bazi ro baladi baiad man ro bezani.\n',
         'had aghal mizashti man mizadam. hal mikardam.\n',
         'khob az aval bego ghasde khod khoshi dari.\n'],
    'after_pTOe_F' :
        ['%^%$# tiret mashghi bod.\n',
         'shans avordam :).\n',
         'he mashghi bod.\n',
         'he he he mage mitoni man ro bezani.\n',
         'khata raft.\n',
         'shahed iek adad noob hastim -_-.\n',
         'to divari aziz, to divari.\n'],
    'after_pTOp_F' :
        ['kheili jorat dari in kar ro kardi\n',
         'bebinam midonesti???\n',
         'az kojat avordiiii.\n',
         'kheili chiz dashti ke in kar ro kardi.\n',
         'ie daghighe fekr kardam mikhai khod koshi koni.\n',
         'az baghal goshet rad shod.\n',
         'aaaa heif shod ke. dashti movafagh mishodi khod koshi koni.\n',],
    'after_eTOe_T' :
        ['az dastam dar raft.\n',
         'bavar kardi khob zani dost daram ia na.\n',
         'inam avanse man be to.\n',
         'badane khodame, dost dashtam behesh shelik konam -_-.\n',
         'in taze ie kocholo az divone baziam bod.\n',
         'aeeeee dard dasht dost dari khodet ham test koni???\n',
         'hala bezar daram barat bishar#$%.\n',
         'he he he aslan ham dard nadasht.\n',
         'kheir nabinammmm.\n'],
    'after_eTOp_T' :
        ['khordi hala hastash ro tof kon.\n',
         'in jash mimone :).\n',
         'baba haftir keshe ki bodam man.\n',
         'in ast ghodrate ie pro player.\n',
         'bazam mikhai haaaa???\n',
         'hala feshar bokhor.\n',
         'dahanet ro saf kardam. dast va jigh va horaaa.\n'],
    'after_eTOe_F' :
        ['midonestam mashghi.\n',
         'ei baba heif shoda mikhastam khod khoshi konam dige roto nabinam.\n',
         'pas kei man mimiram ke dige roto nabinam.\n',
         'are are man cheateram',
         'baba pishgo ki bodam man :).',
         'boooom alaki bod.\n',
         'ta shobade bazi badi by by.\n'],
    'after_eTOp_F' :
        ['naaa joratet ro dost daram.\n',
         'natars baba mashghi bod.\n',
         'in ie bar ro faghat shans avordi.\n',
         'ei babab nashod bemiri ke.\n',
         'dashtam az dastet rahat mishodam.\n'],
    'enemy_gun' : 
        ['khob hala aslahe daste mane.\n',
         'hala marg va zendegi to daste mane :).\n',
         'hala man migam aslahe samte ki bashe.\n',
         'kheili jorat dari ke hanoz hasti.\n',
         'khili chiz dari ke hanoz hasti.\n',
         'kheir nadide nobat mane :).\n'],
    'before_eTOp' : 
        ['khob to saret bezanam ia dahanet???\n',
         'mikham bokoshamet :).\n',
         'bego aaaaa.\n',
         'khob bezar bebinam khonet che rangi???\n',
         'by by bache :),\n',
         'benazaret to saret chi dari???\n',
         'halva sare khaket miaram.\n',
         'ieki kamtar zendegi behtar.\n'],
    'before_eTOe' :
        ['bebin man divonam.\n',
        'alaghe khasi be khod koshi daram.\n',
        'agar zende bemonam mikoshamet.\n',
        'fahmidi man divonam ia na???\n',
        'midonam ke alaki ;).\n',
        'divone bazi dost daram.\n',
        'toie oon donia mibinamet ;).\n'],
    'player_winner_p1' : 
        ['naaaa man moldam :| .\n',
         'chejori chejoriii chjoriiiiiii.\n',
         'bebin man khastsam behet rahm konam vagarna mna mitonestam bebaram.\n',
         'hala ie dast bordi chi shod alan.\n',
         'alan khoshali ke ie bat ro koshti -_-.\n',
         'jorat dari bazam bia bazi.\n',
         'bordan iek robat eftekhar nist.\n'],
    'player_winner_p2' :
        ['tabrik migam shoma barande shodi. khoshhal misham dobare ham bazi koni.\n',
         'tabrik migam shoma bordi shodi. khoshhal misham dobare ham bazi koni.\n',
         'bazi khobi bod. dost dashti dobare ham bazi kon???\n'],
    'enemy_winner_p1' :
        ['he he he bakhti ke!!!.\n',
         'he he he badbakht mordi.\n',
         'bang bang koshtamet.\n',
         'chishod mordi ke.\n',
         'ie adam kamtar zendegi behtar.\n',
         'hamishe ie noob mimire.\n',
         'kheili asoon mordi ke.\n',
         'bozorg mishi marget iadet mire.\n'],
    'enemy_winner_p2' :
        ['dost dashti bazam bazi kon shaiad bordi.\n',
         'ie bare dige bazi kon shaiad bordi.\n',
         'daste bad behtar mishsi.\n',
         'hala eshkal nadare daste badi behtar mishi.\n',],
         
}

def get_text(section):
    return TEXT[section][randint(0 , len(TEXT[section]) - 1)]